// flow-typed signature: 27fe116f7d639fab4f0e6cd8c622648d
// flow-typed version: <<STUB>>/vx-bin_v^0.1.10/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vx-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vx-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vx-bin/bin/vx-bin' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/BuildCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/CleanCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/Cmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/CoverCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/DevCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/FlowCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/GulpCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/gulpfile' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/helper' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/InstallCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/LintCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/PackCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/pkg' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/program' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/PublishCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/TestCmd' {
  declare module.exports: any;
}

declare module 'vx-bin/lib/UnpublishCmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vx-bin/bin/vx-bin.js' {
  declare module.exports: $Exports<'vx-bin/bin/vx-bin'>;
}
declare module 'vx-bin/lib/BuildCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/BuildCmd'>;
}
declare module 'vx-bin/lib/CleanCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/CleanCmd'>;
}
declare module 'vx-bin/lib/Cmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/Cmd'>;
}
declare module 'vx-bin/lib/CoverCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/CoverCmd'>;
}
declare module 'vx-bin/lib/DevCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/DevCmd'>;
}
declare module 'vx-bin/lib/FlowCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/FlowCmd'>;
}
declare module 'vx-bin/lib/GulpCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/GulpCmd'>;
}
declare module 'vx-bin/lib/gulpfile.js' {
  declare module.exports: $Exports<'vx-bin/lib/gulpfile'>;
}
declare module 'vx-bin/lib/helper.js' {
  declare module.exports: $Exports<'vx-bin/lib/helper'>;
}
declare module 'vx-bin/lib/InstallCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/InstallCmd'>;
}
declare module 'vx-bin/lib/LintCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/LintCmd'>;
}
declare module 'vx-bin/lib/PackCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/PackCmd'>;
}
declare module 'vx-bin/lib/pkg.js' {
  declare module.exports: $Exports<'vx-bin/lib/pkg'>;
}
declare module 'vx-bin/lib/program.js' {
  declare module.exports: $Exports<'vx-bin/lib/program'>;
}
declare module 'vx-bin/lib/PublishCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/PublishCmd'>;
}
declare module 'vx-bin/lib/TestCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/TestCmd'>;
}
declare module 'vx-bin/lib/UnpublishCmd.js' {
  declare module.exports: $Exports<'vx-bin/lib/UnpublishCmd'>;
}
